config/routes.rb
Rails.application.routes.draw do
 


 
  resources :ingredients, only: [:index, :create, :new, :show, :update, :edit, :destroy]



  resources :recipes, only: [:index, :create, :new, :show, :update, :edit, :destroy]

  resources :comments, only: [:index, :create, :new, :show, :update, :edit, :destroy]

  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
  get 'login', to: 'devise/sessions#new'
  end
  devise_scope :user do
  get 'signup', to: 'devise/registrations#new'
  end



  get '/recipes/:ingredient_name' => 'recipes#search'

  root 'welcome#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :user
    belongs_to :recipe

   

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

has_many :recipes
belongs_to :recipe

    def ingredient_attributes=(ingredient)
    self.ingredient = Ingredient.find_or_create_by(ingredient_name: ingredient[:ingredient_name])
    self.ingredient.update(ingredient)
    end

end

app/models/recipe.rb
class Recipe < ApplicationRecord

    #belongs_to :user
    has_many :comments
    has_many :users, through: :comments
    has_many :ingredients
    accepts_nested_attributes_for :ingredients, reject_if: lambda {|attributes| attributes['ingredient_name'].blank?}


    def ingredient_attributes=(ingredient)
        self.ingredient = Ingredient.find_or_create_by(ingredient_name: ingredient[:ingredient_name])
        self.ingredient.update(ingredient)
        end



end

app/models/user.rb
class User < ApplicationRecord
  devise :rememberable, :omniauthable, :omniauth_providers => [:facebook]

    has_many :comments
    has_many :recipes, through: :comments
    #has_many :recipes
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
   
    @comments = Comment.all
  end

  def show
      @comments = Comment.where(user_id:(current_user.id))
  end

  def new
 

  end

  def create
    
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    
    @comment.save
    
    redirect_to comment_path(@comment)
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)

    redirect_to comment_path(@comment)
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to "/comments"
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :username, :body, :user_id, :recipe_id, category_ids:[])
  end

end

app/controllers/hw_controller.rb
class HwController < ApplicationController
  def hello_world
    render 'hello_world'
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.save
    redirect_to ingredient_path(@ingredient)
  end

  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:ingredient_name, :recipe_id)
  end


end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env[“omniauth.auth”])
            if @user.persisted?
            sign_in_and_redirect @user, :event => :authentication
            set_flash_message(:notice, :success, :kind => “Facebook”) if is_navigational_format?
            else
            session[“devise.facebook_data”] = request.env[“omniauth.auth”]
            redirect_to new_user_registration_url
            end
    end

    def failure
        redirect_to root_path
    end
    def new_session_path *args 
        new_user_session_path *args
      end
      
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
      @recipes = Recipe.where(user_id:(current_user.id))
  end

  def new
    @recipe = Recipe.new
    12.times { @recipe.ingredients.build}
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    @recipe.save
    redirect_to recipe_path(@recipe)
  end

  def search
    @recipes = Recipe.find_by(params[:ingredient_name])
  end
  







  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    @recipe.ingredient_id = 

    redirect_to recipe_path(@recipe)
  end

  def destroy
    Recipe.find(params[:id]).destroy
    redirect_to "/recipes"
  end

  private

  def ingredient_params
    params.permit(:ingredient_name, :recipe_id)
  end


  def recipe_params
    params.require(:recipe).permit(:name, :username, :description, :instructions, :ingredients, :ingredient_id, ingredients_attributes: [:ingredient_name, :recipe_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: :create

    def create
      @user = User.find_or_create_by(uid: auth['uid']) do |u|
        u.name = auth['info']['name']
        u.email = auth['info']['email']
        u.image = auth['info']['image']
      end
   
      session[:user_id] = @user.id
   
      render 'welcome/home'
    end
   
    private
   
    def auth
      request.env['omniauth.auth']
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
      @user = User.find(params[:id])
  end

  def new
  end

  def create
    @user = User.create(user_params(:name, :bio, :username, :password, :password_confirmation))
    return redirect_to controller: 'users', action: 'new' unless @user.save
    session[:user_id] = @user.id
    redirect_to controller: 'welcome', action: 'home'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params(:name, :bio))

    redirect_to user_path(@user)
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to "/users"
  end

  

  def user_commments
    @user = User.find(params[:id])
    @comment = @user.comments
  end




  private

  def user_params(*args)
    params.require(:user).permit(*args)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController	

 


end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h3> Edit your Comment </h3>

<%= form_for(@comment)  do |f| %>

    <label> Name:</label><br>
    <%= f.text_field :name %><br>

    <label>Username:</label><br>
    <%= f.text_field :username %><br>

    <label>Comment body:</label><br>
    <%= f.text_area :body %><br>

    <%= f.collection_check_boxes :recipe_id, Recipe.all, :id, :name %>

   

    <%= submit_tag "Submit Comment" %>
<% end %>



<%= button_to "Delete", @comment, method: :delete, data: { confirm: "Really?" } %>

<br><%= link_to "Create a recipe", "/recipes/new" %><br>
<%= link_to "View all recipes", "/recipes" %><br>

<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>
<% end %>

app/views/comments/index.html.erb
<p>
<% @comments.each do |comment|%><br><li>
   Name: <%= comment.name %><br>
   Username: <%= comment.username %><br>
   Body: <%= comment.body %><br>
  
   Comment ID: <%=comment.id %>

    
    <% end %>
    </li></p><br>

    <br><%= link_to "Create a recipe", "/recipes/new" %><br>
<%= link_to "View all recipes", "/recipes" %><br>

<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>
<% end %>

app/views/comments/new.html.erb
<h3> Create a Comment </h3>

<%= form_tag comments_path do %>

    <label>Username:</label><br>
    <%= @user.name %><br>

   <br> <label> Name:</label><br>
    <%= text_field_tag :"comment[name]" %><br>



    <label>Comment body:</label><br>
    <%= text_area_tag :"comment[body]" %><br>


    <%= hidden_field_tag :"comment[recipe_id]", params[:id] %>
    <%= hidden_field_tag :"comment[username]", @user.username %>


    <%= submit_tag "Submit Comment" %>

<% end %>

<br><%= link_to "Create a recipe", "/recipes/new" %><br>
<%= link_to "View all recipes", "/recipes" %><br>

<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>
<% end %>

app/views/comments/show.html.erb
<% @comments.each do |comment| %>
    <li>
    Name: <%= comment.name %><br>
    Username: <%= comment.username %><br>
    Body: <%= comment.body %><br>
    User id: <%= comment.user_id %><br>
    Recipe ID: <%=comment.recipe_id%><br>
    Comment ID: <%= comment.id %>
    <% end %>
    </li>
 
    
     
    <br><%= link_to "Create a recipe", "/recipes/new" %><br>
<%= link_to "View all recipes", "/recipes" %><br>

<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>
<% end %>

app/views/hw/hello_world.html.erb
<h1>Hello World</h1>

app/views/ingredients/index.html.erb
<% @ingredients.each do |ingredient| %>
    <li>
   <br>Name: <%=  ingredient.ingredient_name %><br>
   Recipe ID: <%=  ingredient.recipe_id %><br>
    <% end %>
    </li><br>

app/views/ingredients/new.html.erb
<h3> Missing an ingredient you use? Add an Ingredient </h3>

<%= form_for :ingredient, as: :post, url: ingredients_path do |f| %>

    <label> Name:</label><br>
    <%= f.text_field :ingredient_name %><br>

    <%= f.submit  %>
<% end %>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>

Ingredients: <%= @ingredient.ingredient_name %><br>
<%= @ingredient.recipe_id %><br>
<%= @ingredient.id %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helloworldlab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helloworldlab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_links.html.erb
<%= link_to "Create a recipe", "/recipes/new" %><br>
<%= link_to "View all recipes", "/recipes" %><br>

<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>

  <%= render 'links_form' %>

app/views/recipes/_links.html.erb
<br><%= link_to "Create a recipe", "/recipes/new" %><br>
<%= link_to "View all recipes", "/recipes" %><br>
<%= link_to "View my recipes", "/recipes/show" %><br>

<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>
<% end %>
  

app/views/recipes/_recipe_ingredient_form.html.erb
 





<%= f.label :ingredient_name, "Ingredient Name:" %>
<%= f.text_field :ingredient_name %>

app/views/recipes/edit.html.erb
<h3> Edit your Recipe </h3>

<%= form_for(@recipe) do |f| %>

    <label> Name:</label><br>
    <%= f.text_field :name %><br>

    <label>Username:</label><br>
    <%= f.text_field :username %><br>

    <label>Recipe Description:</label><br>
    <%= f.text_area :description %><br>

    <label>Recipe instructions:</label><br>
    <%= f.text_area :instructions %><br>

    <label>Recipe ingredients:</label><br>
    <%= f.text_area :ingredients %><br>

    <%= f.submit %>


    
    

<% end %>

<%= button_to "Delete", @recipe, method: :delete, data: { confirm: "Really?" } %>
<%= render 'links' %>

app/views/recipes/index.html.erb
<p>
<% @recipes.each do |recipe|%><br><li>
   Name: <%= recipe.name %><br>
   Username: <%= recipe.username %><br>
   Description: <%= recipe.description %><br>
   Instructions: <%= recipe.instructions %><br>
   <% recipe.ingredients.each do |i| %>
      Ingredient name: <%= i.ingredient_name %><br>
 
       <% end %>
       <br> Comments:
  <% recipe.comments.each do |comment| %>
    <%= link_to comment.user.username, user_path(comment.user) %> said
    <%= comment.body %>
  <% end %>
   

   <br><%= link_to "create comment", controller: "comments", action: "new", id: recipe.id%><br>
   


    
    <% end %>
    </li></p><br>
    <%= render 'links' %>

app/views/recipes/new.html.erb
<h3> Create a Recipe </h3>

<%= form_for (@recipe) do |f| %>

    <label> Name:</label><br>
    <%= f.text_field :name %><br>

    <label>Recipe Description:</label><br>
    <%= f.text_area :description %><br>

    <label>Recipe instructions:</label><br>
    <%= f.text_area :instructions %><br>

    <%= hidden_field_tag :"recipe[username]", @user.username %>

    

   
    <h3>Ingredients</h3>
 
    
    <%= f.fields_for :ingredients do |ing| %>
    <%= ing.label :ingredient_name, "Ingredient Name:" %>
    <%= ing.text_field :ingredient_name %>

         
    <%= hidden_field_tag :"recipe[ingredient_id]", [:id] %>



           

<% end %>
    <%= f.submit  %>
<% end %>



<%= render 'links' %>

app/views/recipes/search.html.erb
search

app/views/recipes/show.html.erb
<% @recipes.each do |recipe|%><br><li>

   Name: <%= recipe.name %><br>
   Username: <%= recipe.username %><br>
   Description: <%= recipe.description %><br>
   Instructions: <%= recipe.instructions %><br>
   

    <% recipe.ingredients.each do |i| %>
    Ingredient name: <%= i.ingredient_name %><br>
  
     <% end %>

  <br> Comments:
  <% recipe.comments.each do |comment| %>
    <%= link_to comment.user.username, user_path(comment.user) %> said
    <%= comment.body %>
  <% end %>
  </li>

  

  <% end %>
  <%= render 'links' %>

app/views/users/edit.html.erb
<h3> User Edit Form </h3>

<%= form_for(@user) do |f| %>

    <label> Name:</label><br>
    <%= f.text_field :name %><br>

 

    <label>User Bio:</label><br>
    <%= f.text_field :bio %><br>


    <%= f.submit %>
<% end %>

<%= button_to "Delete", @user, method: :delete, data: { confirm: "Really?" } %>

app/views/users/index.html.erb
<p>
<% @users.each do |user|%><br><li>
   Name: <%= user.name %><br>
   Username: <%= user.username %><br>
   Bio: <%= user.bio %><br>
   Password: <%= user.password_digest %><br>

    
    <% end %>
    </li></p><br>

app/views/users/new.html.erb
<h3> User Form </h3>

<%= form_tag users_path do %>

    <label> Name:</label><br>

    <%= text_field_tag :"user[name]" %><br>

    <label>Username:</label><br>

    <%= text_field_tag :"user[username]" %><br>

    <label>User Bio:</label><br>

    <%= text_field_tag :"user[bio]" %><br>

    <label>User Password:</label><br>

    <%= text_field_tag :"user[password]" %><br>

    <%= submit_tag "Submit User" %>
<% end %>

app/views/users/show.html.erb
<h1> This is your information </h1>


    Name: <%= @user.name %><br>
    Username: <%= @user.username %><br>
    Bio: <%= @user.bio %><br>

    <h2><%= @user.username %> </h2> has commented on the following recipes:
 
<% @user.recipes.each do |recipe| %><br>
  Recipe  <%= link_to recipe.name, recipe_path(recipe) %>
<% end %>




<% @user.comments.each do |comment| %><br>
   Comment  <%= link_to comment.name, recipe_path(recipe_url) %>
  <% end %>
   
 

app/views/welcome/home.html.erb
<div>
<%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
  </div>